-- LAB-RESEARCH-001 · Trade Committee persistent run log
-- Append-only history: every Committee execution receives its own run_id.

create table if not exists public.trade_committee_runs (
    id bigint generated by default as identity primary key,
    run_id text not null unique,
    ticker text not null,
    status text not null check (status in ('RUNNING','COMPLETE','FAILED')),
    started_at timestamptz not null default now(),
    finished_at timestamptz,
    verdict text,
    committee_score numeric,
    data_confidence numeric,
    warning_count integer not null default 0,
    error_type text,
    error_message text,
    error_trace text,
    result_payload jsonb,
    created_at timestamptz not null default now()
);

create index if not exists idx_trade_committee_runs_started_at
    on public.trade_committee_runs (started_at desc);
create index if not exists idx_trade_committee_runs_ticker_started
    on public.trade_committee_runs (ticker, started_at desc);

create table if not exists public.trade_committee_run_steps (
    id bigint generated by default as identity primary key,
    run_id text not null references public.trade_committee_runs(run_id) on delete cascade,
    step_no integer not null,
    label text not null,
    status text not null check (status in ('COMPLETE','WARNING','FAILED','RUNNING')),
    note text,
    logged_at timestamptz not null default now(),
    unique(run_id, step_no)
);

create index if not exists idx_trade_committee_steps_run
    on public.trade_committee_run_steps (run_id, step_no);

alter table public.trade_committee_runs enable row level security;
alter table public.trade_committee_run_steps enable row level security;

-- Server-side service role bypasses RLS. No anonymous/user policies are created.
comment on table public.trade_committee_runs is 'Persistent LAB-RESEARCH-001 run history; service-role access only.';
comment on table public.trade_committee_run_steps is 'Step-level diagnostics for Trade Committee runs; service-role access only.';
