create table if not exists public.system_run_log (
  id bigint generated by default as identity primary key,
  run_key text not null unique,
  module text not null,
  component text,
  workflow text,
  market text,
  status text not null default 'RUNNING',
  trigger_source text,
  github_run_id text,
  github_run_attempt text,
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  duration_seconds numeric,
  processed_count integer not null default 0,
  action_count integer not null default 0,
  sent_count integer not null default 0,
  skipped_count integer not null default 0,
  error_count integer not null default 0,
  message text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint system_run_log_status_chk check (status in ('RUNNING','OK','ERROR','CANCELLED','SKIPPED')),
  constraint system_run_log_counts_chk check (
    processed_count >= 0 and action_count >= 0 and sent_count >= 0 and skipped_count >= 0 and error_count >= 0
  )
);

create index if not exists idx_system_run_log_module_started
  on public.system_run_log(module, started_at desc);
create index if not exists idx_system_run_log_status_started
  on public.system_run_log(status, started_at desc);
create index if not exists idx_system_run_log_workflow_started
  on public.system_run_log(workflow, started_at desc);

comment on table public.system_run_log is
  'Operational heartbeat and execution ledger for scheduled/manual trading-engine processes.';
comment on column public.system_run_log.run_key is
  'Unique execution key, normally module + GitHub run id + attempt + job/market.';
comment on column public.system_run_log.status is
  'Execution status: RUNNING, OK, ERROR, CANCELLED or SKIPPED.';
