-- Trading Lab PostgreSQL/Supabase schema

create table if not exists engine_runs (
    id bigint generated by default as identity primary key,
    run_id text unique not null,
    run_timestamp timestamptz default now(),
    market text,
    horizon text,
    engine_version text,
    config_version text,
    universe_size integer,
    candidates_count integer,
    notes text
);

create table if not exists signals (
    id bigint generated by default as identity primary key,
    signal_id text unique not null,
    run_id text references engine_runs(run_id) on delete cascade,
    created_at timestamptz default now(),
    market text,
    ticker text not null,
    horizon text,
    price numeric,
    status text,
    decision text,
    setup text,
    trigger text,
    score_total numeric,
    score_quality numeric,
    score_value numeric,
    score_growth numeric,
    score_solidarity numeric,
    score_management numeric,
    score_catalyst numeric,
    score_trend numeric,
    score_volume_rs numeric,
    score_entry_rr numeric,
    score_diversification numeric,
    entry numeric,
    buy_range_low numeric,
    buy_range_high numeric,
    max_buy numeric,
    stop numeric,
    tp1 numeric,
    tp2 numeric,
    rr_gross_tp1 numeric,
    rr_gross_tp2 numeric,
    rr_net_tp1 numeric,
    rr_net_tp2 numeric,
    qty integer,
    capital numeric,
    loss_max numeric,
    sma20 numeric,
    sma50 numeric,
    sma200 numeric,
    rsi14 numeric,
    macd numeric,
    atr14 numeric,
    rs_5d numeric,
    rs_20d numeric,
    rs_60d numeric,
    rs_120d numeric,
    volume numeric,
    avg_volume_10 numeric,
    avg_volume_50 numeric,
    relative_volume numeric,
    earnings_date date,
    days_to_earnings integer,
    data_quality text,
    reason text,
    raw_data jsonb
);

create table if not exists signal_outcomes (
    id bigint generated by default as identity primary key,
    signal_id text unique references signals(signal_id) on delete cascade,
    price_d1 numeric,
    price_d3 numeric,
    price_d5 numeric,
    price_d10 numeric,
    price_d20 numeric,
    price_d60 numeric,
    return_d1 numeric,
    return_d3 numeric,
    return_d5 numeric,
    return_d10 numeric,
    return_d20 numeric,
    return_d60 numeric,
    mfe_5d numeric,
    mae_5d numeric,
    mfe_20d numeric,
    mae_20d numeric,
    mfe_60d numeric,
    mae_60d numeric,
    hit_stop boolean default false,
    hit_tp1 boolean default false,
    hit_tp2 boolean default false,
    days_to_stop integer,
    days_to_tp1 integer,
    days_to_tp2 integer,
    updated_at timestamptz default now()
);

create table if not exists trades (
    id bigint generated by default as identity primary key,
    signal_id text references signals(signal_id),
    ticker text not null,
    market text,
    broker text default 'Fineco',
    order_date timestamptz,
    entry_date timestamptz,
    order_type text,
    qty integer,
    entry_price numeric,
    stop_initial numeric,
    stop_current numeric,
    tp1 numeric,
    tp2 numeric,
    exit_date timestamptz,
    exit_price numeric,
    commission_entry numeric,
    commission_exit numeric,
    gross_pnl numeric,
    net_pnl numeric,
    return_pct numeric,
    trade_status text,
    exit_reason text,
    created_at timestamptz default now()
);

create table if not exists trade_events (
    id bigint generated by default as identity primary key,
    trade_id bigint references trades(id) on delete cascade,
    created_at timestamptz default now(),
    event_type text,
    old_value text,
    new_value text,
    note text
);

create table if not exists watchlist (
    id bigint generated by default as identity primary key,
    ticker text not null,
    market text,
    status text,
    alert_type text,
    alert_price numeric,
    reason text,
    source_signal_id text references signals(signal_id),
    created_at timestamptz default now(),
    expires_at timestamptz,
    active boolean default true
);

create table if not exists engine_config (
    id bigint generated by default as identity primary key,
    config_version text unique not null,
    valid_from timestamptz default now(),
    min_score_buy numeric,
    min_rr numeric,
    max_position numeric default 2500,
    commission numeric default 12,
    parameters jsonb
);

create index if not exists idx_signals_ticker on signals(ticker);
create index if not exists idx_signals_created_at on signals(created_at desc);
create index if not exists idx_signals_status on signals(status);
create index if not exists idx_signals_horizon on signals(horizon);
create index if not exists idx_signals_run_id on signals(run_id);
create index if not exists idx_watchlist_ticker on watchlist(ticker);
create index if not exists idx_watchlist_active on watchlist(active);
create index if not exists idx_trades_ticker on trades(ticker);
create index if not exists idx_trades_status on trades(trade_status);

insert into engine_config (config_version, min_score_buy, min_rr, max_position, commission, parameters)
values (
    '2.0-initial', 70, 2.0, 2500, 12,
    '{"weights":{"quality":15,"value":15,"growth":12,"solidarity":12,"management":8,"catalyst":8,"trend":12,"volume_rs":6,"entry_rr":8,"diversification":4}}'::jsonb
)
on conflict (config_version) do nothing;
