create table if not exists lab_backtest_runs (
  id bigint generated by default as identity primary key,
  run_id text unique not null,
  created_at timestamptz default now(),
  mode text not null,
  engine_version text,
  symbols text[],
  strategies text[],
  status text not null default 'RUNNING',
  notes text
);

create table if not exists lab_backtest_results (
  id bigint generated by default as identity primary key,
  run_id text references lab_backtest_runs(run_id) on delete cascade,
  symbol text not null,
  strategy text not null,
  trades integer,
  win_rate numeric,
  avg_return_pct numeric,
  profit_factor numeric,
  net_pnl numeric,
  return_pct numeric,
  final_equity numeric,
  data_status text default 'OK',
  error text,
  metrics jsonb,
  created_at timestamptz default now()
);

create table if not exists lab_calibration_results (
  id bigint generated by default as identity primary key,
  run_id text references lab_backtest_runs(run_id) on delete cascade,
  symbol text not null,
  strategy text not null,
  entry_score numeric,
  atr_stop_mult numeric,
  target_r_multiple numeric,
  train_return_pct numeric,
  test_return_pct numeric,
  test_trades integer,
  promoted boolean default false,
  created_at timestamptz default now()
);

create table if not exists lab_paper_signals (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  symbol text not null,
  strategy text not null,
  signal_date date not null,
  score numeric,
  price numeric,
  proposed_entry numeric,
  proposed_stop numeric,
  proposed_target numeric,
  status text not null default 'PAPER_ONLY',
  details jsonb,
  unique(symbol, strategy, signal_date)
);

create index if not exists idx_lab_results_run on lab_backtest_results(run_id);
create index if not exists idx_lab_results_strategy on lab_backtest_results(strategy);
create index if not exists idx_lab_paper_date on lab_paper_signals(signal_date desc);
