create table if not exists lab_strategy_variants (
  id bigint generated by default as identity primary key,
  variant_id text unique not null,
  parent_strategy text not null,
  parent_variant_id text,
  generation integer not null default 1,
  created_at timestamptz default now(),
  parameters jsonb not null,
  mutation_reason text,
  status text not null default 'CANDIDATE',
  promoted_to_core boolean not null default false,
  notes text
);

create table if not exists lab_strategy_evaluations (
  id bigint generated by default as identity primary key,
  evaluation_id text unique not null,
  variant_id text not null references lab_strategy_variants(variant_id) on delete cascade,
  symbol text not null,
  created_at timestamptz default now(),
  train_return_pct numeric,
  oos_return_pct numeric,
  train_profit_factor numeric,
  oos_profit_factor numeric,
  train_trades integer,
  oos_trades integer,
  train_max_drawdown_pct numeric,
  oos_max_drawdown_pct numeric,
  robustness_score numeric,
  verdict text not null,
  details jsonb
);

create index if not exists idx_strategy_variants_parent on lab_strategy_variants(parent_strategy, generation);
create index if not exists idx_strategy_variants_status on lab_strategy_variants(status);
create index if not exists idx_strategy_eval_variant on lab_strategy_evaluations(variant_id);
create index if not exists idx_strategy_eval_verdict on lab_strategy_evaluations(verdict);
