-- Trading Lab operational state: watchlist, paper positions and lifecycle events.
-- Research-only. These tables are intentionally separate from Core trades/watchlist.

create table if not exists lab_watchlist (
    id bigint generated by default as identity primary key,
    symbol text not null,
    strategy text not null,
    market text default 'USA',
    status text not null,
    score numeric,
    price numeric,
    entry numeric,
    max_buy numeric,
    stop numeric,
    tp1 numeric,
    tp2 numeric,
    trigger text,
    alert_type text,
    alert_price numeric,
    distance_to_entry_pct numeric,
    reason text,
    signal_date date,
    last_seen_at timestamptz default now(),
    active boolean default true,
    details jsonb default '{}'::jsonb,
    unique(symbol, strategy)
);

create table if not exists lab_paper_positions (
    id bigint generated by default as identity primary key,
    symbol text not null,
    strategy text not null,
    market text default 'USA',
    source_signal_date date,
    opened_at timestamptz default now(),
    entry_price numeric not null,
    qty integer not null,
    capital numeric not null,
    commission_entry numeric default 12,
    stop_initial numeric,
    stop_current numeric,
    tp1 numeric,
    tp2 numeric,
    last_price numeric,
    last_checked_date date,
    status text default 'OPEN',
    tp1_hit_at timestamptz,
    closed_at timestamptz,
    exit_price numeric,
    exit_reason text,
    gross_pnl numeric,
    net_pnl numeric,
    return_pct numeric,
    details jsonb default '{}'::jsonb
);

create unique index if not exists uq_lab_paper_position_open
on lab_paper_positions(symbol, strategy)
where status in ('OPEN','TP1_HIT');

create table if not exists lab_paper_events (
    id bigint generated by default as identity primary key,
    position_id bigint not null references lab_paper_positions(id) on delete cascade,
    created_at timestamptz default now(),
    event_type text not null,
    price numeric,
    old_stop numeric,
    new_stop numeric,
    note text,
    details jsonb default '{}'::jsonb
);

create index if not exists idx_lab_watchlist_active on lab_watchlist(active, last_seen_at desc);
create index if not exists idx_lab_watchlist_symbol on lab_watchlist(symbol);
create index if not exists idx_lab_paper_positions_status on lab_paper_positions(status);
create index if not exists idx_lab_paper_positions_symbol on lab_paper_positions(symbol);
create index if not exists idx_lab_paper_events_position on lab_paper_events(position_id, created_at desc);
