-- Trading Lab feedback loop: outcomes for every generated signal, including blocked/rejected candidates.
-- Run once in Supabase after 03_strategy_evolution.sql and 04_lab_operational_tables.sql.

create table if not exists lab_signal_outcomes (
    id bigint generated by default as identity primary key,
    symbol text not null,
    strategy text not null,
    signal_date date not null,
    source_signal_status text,
    strategy_score numeric,
    trade_score numeric,
    portfolio_fit_score numeric,
    block_reasons jsonb default '[]'::jsonb,
    regime_state text,
    entry_reference numeric not null,
    stop_reference numeric,
    tp1_reference numeric,
    tp2_reference numeric,
    risk_per_share numeric,
    ret_d1 numeric,
    ret_d3 numeric,
    ret_d5 numeric,
    ret_d10 numeric,
    ret_d20 numeric,
    ret_d60 numeric,
    excess_ret_d1 numeric,
    excess_ret_d3 numeric,
    excess_ret_d5 numeric,
    excess_ret_d10 numeric,
    excess_ret_d20 numeric,
    excess_ret_d60 numeric,
    mfe_pct numeric,
    mae_pct numeric,
    mfe_r numeric,
    mae_r numeric,
    bars_to_mfe integer,
    bars_to_mae integer,
    last_horizon integer default 0,
    last_evaluated_at timestamptz default now(),
    details jsonb default '{}'::jsonb,
    unique(symbol, strategy, signal_date)
);

create index if not exists idx_lab_signal_outcomes_date
on lab_signal_outcomes(signal_date desc);

create index if not exists idx_lab_signal_outcomes_strategy
on lab_signal_outcomes(strategy, signal_date desc);

create index if not exists idx_lab_signal_outcomes_status
on lab_signal_outcomes(source_signal_status);
