create table if not exists core_high_conviction_signals (
    id bigint generated by default as identity primary key,
    run_id text not null,
    created_at timestamptz not null default now(),
    market text not null,
    ticker text not null,
    company_name text,
    signal_class text not null,
    decision text,
    display_state text,
    operational_state text,
    prebuy_score numeric,
    prebuy_label text,
    prebuy_eligible boolean,
    quality_score numeric,
    opportunity_score numeric,
    signal_price numeric,
    buy_zone_low numeric,
    buy_zone_high numeric,
    entry numeric,
    max_buy numeric,
    stop numeric,
    tp1 numeric,
    tp2 numeric,
    gross_rr_tp1 numeric,
    net_rr_tp1 numeric,
    gross_rr_tp2 numeric,
    net_rr_tp2 numeric,
    trigger text,
    missing_gates jsonb default '[]'::jsonb,
    risk_usd numeric,
    risk_pct numeric,
    coverage_pct numeric,
    change_state text,
    active boolean not null default true,
    fast_state text,
    last_price numeric,
    last_checked_at timestamptz,
    email_notified boolean not null default false,
    whatsapp_notified boolean not null default false,
    payload jsonb default '{}'::jsonb,
    unique(run_id, market, ticker)
);

create index if not exists idx_core_hc_active_market
    on core_high_conviction_signals(active, market, created_at desc);

create index if not exists idx_core_hc_ticker_history
    on core_high_conviction_signals(market, ticker, created_at desc);

comment on table core_high_conviction_signals is
'Immutable-per-run Core BUY / high PRE-BUY snapshots for dashboard and notification audit. Trading logic remains in the Core engines.';
