-- Laboratory 2.2 architecture: fill-level execution, atomic aggregation runs and dashboard snapshots.
-- Research-only. Production/Core tables are intentionally untouched.

create table if not exists lab_paper_fills (
    id bigint generated by default as identity primary key,
    position_id bigint not null references lab_paper_positions(id) on delete cascade,
    strategy text not null,
    strategy_version text,
    symbol text not null,
    side text not null default 'LONG' check (side in ('LONG','SHORT')),
    fill_type text not null check (fill_type in ('ENTRY','TP1','TP2','STOP','MANUAL_EXIT')),
    qty integer not null check (qty >= 0),
    price numeric not null,
    commission numeric default 0,
    slippage_bps numeric,
    executed_at timestamptz not null default now(),
    details jsonb default '{}'::jsonb
);
create unique index if not exists uq_lab_paper_fill_event on lab_paper_fills(position_id, fill_type, executed_at, price, qty);
create index if not exists idx_lab_paper_fills_position on lab_paper_fills(position_id, executed_at);

create table if not exists lab_aggregation_runs (
    id bigint generated by default as identity primary key,
    started_at timestamptz not null default now(),
    completed_at timestamptz,
    status text not null default 'PENDING' check (status in ('PENDING','COMPLETED','FAILED')),
    source_run_id text,
    session date not null default current_date,
    expected_rows integer,
    written_rows integer,
    validation_status text,
    error_message text,
    details jsonb default '{}'::jsonb
);
create index if not exists idx_lab_aggregation_runs_status on lab_aggregation_runs(status, completed_at desc, started_at desc);

create table if not exists lab_control_snapshot_daily (
    id bigint generated by default as identity primary key,
    aggregation_run_id bigint not null references lab_aggregation_runs(id) on delete cascade,
    session date not null,
    run_status text,
    data_status text,
    raw_freshness_status text,
    lifecycle_freshness_status text,
    snapshot_freshness_status text,
    signals integer default 0,
    data_valid integer default 0,
    valid_setups integer default 0,
    triggered integer default 0,
    tier_a integer default 0,
    tier_b integer default 0,
    tier_c integer default 0,
    paper_opened integer default 0,
    open_positions integer default 0,
    closed_positions integer default 0,
    data_rejects integer default 0,
    mtm_r numeric,
    open_risk_r numeric,
    locked_profit_r numeric,
    paper_net_pnl numeric,
    updated_at timestamptz not null default now(),
    unique(aggregation_run_id)
);
create index if not exists idx_lab_control_snapshot_session on lab_control_snapshot_daily(session desc, updated_at desc);

create table if not exists lab_strategy_summary_daily (
    id bigint generated by default as identity primary key,
    aggregation_run_id bigint not null references lab_aggregation_runs(id) on delete cascade,
    session date not null,
    strategy text not null,
    strategy_version text not null default 'UNVERSIONED',
    signals integer default 0,
    eligible integer default 0,
    paper_opened integer default 0,
    open integer default 0,
    closed integer default 0,
    wins integer default 0,
    losses integer default 0,
    win_rate numeric,
    net_pf numeric,
    expectancy_r numeric,
    realized_r numeric,
    mtm_r numeric,
    avg_return_pct numeric,
    max_drawdown_r numeric,
    open_risk_r numeric,
    locked_profit_r numeric,
    mfe_r_median numeric,
    mae_r_median numeric,
    main_blocker text,
    main_blocker_pct numeric,
    blocker_sample integer default 0,
    maturity text,
    verdict text,
    verdict_reason_codes jsonb default '[]'::jsonb,
    verdict_policy_version text,
    stress_status text,
    stress_reason_codes jsonb default '[]'::jsonb,
    stress_policy_version text,
    updated_at timestamptz not null default now(),
    unique(aggregation_run_id, strategy, strategy_version)
);
create index if not exists idx_lab_strategy_summary_strategy on lab_strategy_summary_daily(strategy, session desc);

create table if not exists lab_strategy_ticker_snapshot (
    id bigint generated by default as identity primary key,
    aggregation_run_id bigint not null references lab_aggregation_runs(id) on delete cascade,
    session date not null,
    strategy text not null,
    strategy_version text not null default 'UNVERSIONED',
    symbol text not null,
    tier text,
    state text,
    side text default 'LONG',
    sector text,
    correlation_cluster text,
    cluster_avg_correlation numeric,
    fill_price numeric,
    current_price numeric,
    stop_current numeric,
    tp1 numeric,
    tp2 numeric,
    trading_days integer,
    net_return_pct numeric,
    mtm_r numeric,
    open_risk_r numeric,
    locked_profit_r numeric,
    updated_at timestamptz not null default now(),
    unique(aggregation_run_id, strategy, strategy_version, symbol)
);
create index if not exists idx_lab_strategy_ticker_strategy on lab_strategy_ticker_snapshot(strategy, session desc);

alter table lab_paper_positions add column if not exists side text default 'LONG';
alter table lab_paper_positions add column if not exists strategy_version text;
alter table lab_paper_positions add column if not exists ideal_entry numeric;
alter table lab_paper_positions add column if not exists fill_price numeric;
alter table lab_paper_positions add column if not exists atr14_at_entry numeric;
alter table lab_paper_positions add column if not exists raw_initial_risk numeric;
alter table lab_paper_positions add column if not exists normalized_initial_risk numeric;
alter table lab_paper_positions add column if not exists risk_floor_applied boolean default false;
alter table lab_paper_positions add column if not exists realized_r numeric;
alter table lab_paper_positions add column if not exists mtm_r numeric;
alter table lab_paper_positions add column if not exists open_risk_r numeric;
alter table lab_paper_positions add column if not exists locked_profit_r numeric;
