-- Tracks each lab_strategy_evolution.py run so failures are queryable
-- from Supabase instead of only being printed to GitHub Actions logs.

create table if not exists lab_evolution_runs (
  id bigint generated by default as identity primary key,
  run_stamp text unique not null,
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  status text not null default 'RUNNING',
  symbols_requested text[],
  strategies_requested text[],
  variants_written integer default 0,
  evaluations_written integer default 0,
  promotable_variants integer default 0,
  symbol_failures jsonb default '[]'::jsonb,
  variant_write_failures jsonb default '[]'::jsonb,
  notes text
);

create index if not exists idx_lab_evolution_runs_status on lab_evolution_runs(status);
create index if not exists idx_lab_evolution_runs_started on lab_evolution_runs(started_at);
